### ISSUE TITLE
目标还是要有的

### ISSUE THREAD

**Issue by cosven** [cosven/cosven.github.io#42]
写好看的代码 ~ 解决自己遇到的实际问题 -> 要酷

或许某天还是会把这种笔记放入私人文件夹。
### Goals Overview
- [ ] 提升写可维护的工具的能力
- [ ] 增长见识，各方面，技术，生活，音乐，历史，小说？
- [ ] 提升表达能力
#### day plan (两天为单位比较科学)
1. 看任意一本技术书籍的一小节以提高编码能力。成果：写小段代码或者读书感悟
2. **阅读** 任意一短篇文学作品 或者 2-3页杂志类以提高见识 或者 交流沟通类。成果：写一段读后感或者随便扯一扯。
3. 程序员（互联网相关即可）的新闻一则。成果：写下感受
#### 2016 Objective
- [x] 能自言自语半小时。(2016-11-21：经过近几个月测试，发现没什么压力)
- [ ] 写一个 代码比较干净，测试率达到 60% 的项目
- [ ] 能有 5 篇字数 1000 左右的 notes | post
    - [x] <https://github.com/cosven/cosven.github.io/issues/43#issuecomment-263547301>
- [ ] 在一群人谈话时，能正确的插上 3 句话。（2016-11-21：此目标不好玩）
- [x] 在京结交一个同年龄、靠谱的同性朋友 和 一个差不多年龄、有共同价值观的异性朋友。(2016-11-21：这个先算作是 80% finished 好了...)

###### 如何让下班之后的生活变得丰富多彩、健康积极？

> **坚持做一些小事情。**
> 跑步、画画、做饭、背单词、看书、摄影。
> 
> 这些答案看似也太平凡了，老生常谈了。关键还是看自己兴趣吧：自己比较喜欢画画，编程，听音乐，悠闲一点的生活。对于画画，感觉没天赋啊，应该只能苦学多练了；编程，同理把；听音乐嘛，这种事情，可以考虑多听点「古典音乐」，时长长点的；悠闲的生活又是啥呢？散步，看书，这些活动都是悠闲生活的体现，怎样创造这样一种生活体验呢，**关键还是 凡事要看得开吧，该分享的分享，该说的说**。
###### 用 Python 写一个 signal/slot 机制
- [一个参考例子](http://code.activestate.com/recipes/577980-improved-signalsslots-implementation-in-python/)
- [django 中的 signal 实现](https://github.com/django/django/blob/master/django/dispatch/dispatcher.py#L4)

> - [x] 不知道为什么要用 weakref ?
>   又折腾了一番 单元测试，怎样科学的写单元测试。
> - 怎样 mock 类函数：使用 mock.patch.object
> - 怎样 mock 函数：mock.patch
#### 2016-9-21

没有看啥文章，倒是走了 14290 步。诶，换了手机，有了计步这么个功能，不过让我惊讶的是，你们每天为什么可以只走 2000、3000 步嘛。简直难以想象好嘛！每天仅仅上下班也会有 6000 步耶，额。（有点女生口吻的感觉...）

可以可以不写感受啊？
###### 这样做朋友，才会天才地久 - 三毛

友谊 - 爱情那一类的情感...
**朋友的可贵就在于自由**，说的太对 ~
不强人所难 ？恩啊，从不！
见人只说三分话 -> 大概是指同事关系 ...
死缠烂打？世上不存在一个人离开你就不能活下去，呃呃呃。哈哈哈
朋友：最美在于 _锦上添花_。淡而不涩 ？
朋友 -> 手足？两性朋友 <-> 婚姻 <-> 取舍

境界略高，何时能及？大概是道理我都懂的感觉...

明天听这个吧 http://www.ximalaya.com/9887414/sound/21522696 这样就不需要找了...
###### <小宇 - 张震岳> 听后感

http://www.xiami.com/song/76287?from=search_popup_song

还是闲扯。今天循环了一天 - -. 除了下午愉快的开黑时光。
一开始看到小宇这种歌名，随意的听了听，以为这是阿岳（这要称呼也是醉醉的）对一个生病的小孩纸唱的，不要问我为什么，大概是第六感。
但是呢，我看到了一些'奇怪'的评论:

> 一个很好的哥们儿看了我歌单后问我：“还是忘不了她吗？”我说“早忘了。”“我还没说是谁呢…”无言以对

额，惊呆了。但是我觉得这首歌更好听了耶....

```
不管未来会怎么样，至少我们现在很开心
不管结局会怎么样，至少想（相）念的人是你（_并不能正确识别后鼻音_）
我不管......，我只想每天都在一起
```

恩，既然是这样的话，那大概就是首情歌了吧。
但是，还是有问题，专辑 <OK> 的整体调调不是这样的啊？

哎，先不管专辑。歌词也很美的 ~ （此时此刻，我多么希望我能写出能看的文字，而不是语句不通顺，以后再看就想删的因果关系句，恩，不管 ！）

开头说 “比方说当我遇见你”，感觉这一句很 `微妙`（微妙这个词真的很微妙...恩，真的很微妙），主要是 “比方” 这个词。我认为呢，‘比方说’ 让遇见变得更有意境 =.=
中间：“我不会把它当做游戏，因为我真心对你” 像这种话，应该还是挺感人(动)的。
”总有些话是不能提，怕你会掉入选择题“ 恩，说得很好...
”如果你还是没法相信，真的没关系，我会安静的离去“ 哈哈，真的没关系（脑补一下说话时的口吻）
- [ ] 我突然想了解了解 ‘张震岳’，这人很有意思。一次是唱 ”思念是一种病 live“ 的时候，竟然哭了，恩，是个有真情实感的人吧。 之前听 ‘谢春花’ 说：她写歌只是纯粹的表达自己当时的一种情感。没必要过度解读，没必要打任何标签。
###### feeluown-core 编写
- [ ] 多进程怎么方便的进行测试
- [x] 多线程 Siganl 实现？非主线程怎样让主线程函数运行一个函数，还是说这是个伪需求？[fuocore](https://github.com/cosven/feeluown-core/issues/2)
  - [ ] python 自带的 signal 是个什么东西？
  - [x] Queue 能解决这个问题么？
    貌似不能直接解决诶
  - [x] django 中 Signal 也没有对线程进行特别处理
- [x] https://github.com/taizilongxu/douban.fm/blob/master/doubanfm/player.py 或许可以参考
  - [x] douban.fm / musicbox 播放器怎样检测当前歌曲播放完了？ 子线程生成孙子线程 -> 迭代下去
###### 祝你一路顺风...

突然看到这么一段故事 https://www.zhihu.com/question/40237308/answer/125609768
虽然比他们大了几岁，但是这个年纪还是非常能体会那种情感的...
再想想现在自己的境况，简直...
恩，决定写一篇日记...
###### 八皇后问题几种算法
- [ ] 待读 https://zhuanlan.zhihu.com/p/22846106
- [ ] 待尝试 https://github.com/neovim/python-client/issues/229#issuecomment-252708313
###### 泛型，强/弱类型，动/静态语言

泛型：大概是能支持运算符重载。[duck typing](https://zh.wikipedia.org/wiki/%E9%B8%AD%E5%AD%90%E7%B1%BB%E5%9E%8B)

https://www.zhihu.com/question/19918532/answer/21645395
强类型：偏向于不容忍隐式类型转换。譬如说haskell的int就不能变成double
弱类型：偏向于容忍隐式类型转换。譬如说C语言的int可以变成double
静态类型：编译的时候就知道每一个变量的类型，因为类型错误而不能做的事情是语法错误。
动态类型：编译的时候不知道每一个变量的类型，因为类型错误而不能做的事情是运行时错误。
###### python 序列化和反序列化慢的原因

创建的了许多对象，GC 疯狂运作？
###### idiom

性格脾气是主食，才华理想是调味剂。

###### flask logging
不行就看 source code ...
flask v0.11 版本自带了生产环境的 log，但是 0.10 没有诶。看着 0.11 的代码，用着 0.10 的版本，然后去 debug，我也是醉醉了 ... 关键是：我以为我是最新版啊 ... 公司的 mirror 没有最新版 ... 隐藏的坑

- [ ] sentry 原理是啥？
- [ ] docker volume 具体是个啥东西，为啥不是 src dst 这种模式？

**Comment by cosven** [comment]
当看到自己曾经把这样的目标写到这个地方，我是很佩服我自己的勇气的。分分钟想删掉...
- [-] 在京结交一个同年龄、靠谱的同性朋友 和 一个差不多年龄、有共同价值观的异性朋友。

**Comment by cosven** [comment]
#### 2016-11-21

###### 记初雪
今日初❄️，大风，完。

\- 雪雪雪雪雪
\- 诶诶诶诶诶
\- (哈哈)

One Q：到底要不要玩游戏呢？大概是不要经常玩...
还有个问题：到底要不要每天 _写一段读后感或者随便扯一扯_ ？答案是，好难写。还不如每天记一两句歌词玩玩 😏，感觉 **可以** ...

诶诶诶，我身后的这位朋友是什么时候把电脑拿走的... [有木有一脸懵逼的表情...]

听 “Casablanca”，问：一个正常人是怎样从 “It's my life / this is suffering” 听到 “Casablanca / Hero” 的 ... 要我说，还是周杰伦好听 -. -

为什么会有区别呢：`-. -` `- .-` `- . -` `-.-` `- -`

写这种东西貌似都是在不想打游戏，也不想写代码，也不知道看啥电影的时候。😝，也是无聊得不要不要的？明明就是懒 》。《

更新频率由 1/pd -> 1/2pd -> 1/10d -> 1/5d，额 ...

"Everlasting Truth - Re:plus" 这首前面听起来很清新脱俗的感觉，哈哈哈
"Yo Te Amo - Chayanne" 这人唱的天生就很深情 q.q 就像是在向某人倾诉什么一样
恩，QQ 音乐 - 
盘点一下：LP 一类 -> MC 一类 -> 双J 一类... 年轻 -> 正常 -> 老年 呃呃呃

哦，还体验了一把冬天穿拖鞋出门。 -> 应该不会想体验第三次 -.- 爽爽滴...

###### Replace Constructor with Factory Method
> 重构：以工厂函数取代构造函数

当你希望在创建对象时不仅仅是简单的创建动作。
比如在创建之前需要进行 validation。恩，想起来今天在纠结的 `JokerymlParser` ...

这本书很实用诶！！！不错的样纸 ~《Refactoring》

**Comment by cosven** [comment]
#### 2016-11-22

###### 走在路上能飞起来
早起的好处是让自己觉得自己只有 18 岁呢
早睡的话，也没老多少吧，说不定还可以让自己以后多健康的活几年呢 - - 嘻嘻嘻。怎么算都不亏

**Comment by cosven** [comment]
#### 2016-11-24

##### gg, lol

##### 以明确函数取代参数 vs 另函数携带参数？
例子还是有区别的 ~

00:20 自己总结是这样：参数如果表示程度，那么很有可能要 **以明确函数取代参数**。如果参数代表种类，那么很有可能是使用 **另函数携带参数**

00:25 或许是主要看共用的逻辑多不多

**Comment by cosven** [comment]
#### 2016-11-25

##### Emacs
Q: 为毛要用 Emacs？
A: 因为想学 Lisp
Q: 为啥要学 Lisp？
A: 看起来好玩。seems cool ~

##### 什么歌曲最适宜写代码？
[see green see blue](http://music.163.com/#/song?id=22492631)
好想知道这个中文翻译是出自哪位之手诶，太符合这歌曲的感觉了 Q~Q

不吵的歌曲很少诶，梁祝算一首 ~
能让人静下心来、不浮(fou)躁(zao)的歌曲应该只有她了... `tmp` 2:16

恩，再来纠结一下：是去杭州玩呢（想去不方便），还是听 live 呢（不太想去但应该去），还是码代码（不怎么想写但应该写），还是应该干点其它事情呢，有啥可以做的吗，玛德...

为啥这 github 不能给 comment 贴标签嘞，不然我就弄个 `玛蛋` 的 label...

伟大的毛主席说过（哈哈哈呵呵呵）：与天斗，其乐无穷。（还是与地斗，其乐无穷去了，忘了）

意象：
- morning coffee
- typewriter
- cardboard sheets
- sea
- blue & green
- Montreal, France

> this is crazy, 

躺沙发睡觉应该是一个很有 年龄感 的趣事 ~

i，Practices proved that 『手抖删游戏真不是一个好习惯』 -. - 恩，这个表情才是正确的使用姿势....

**Comment by cosven** [comment]
#### 2016-11-28

前天听到一句话，大概是讲：**虽然入游戏这个坑，但我是不后悔的**。有且只有一次听到！！！

**Comment by cosven** [comment]
#### 2016-11-29

半岛铁盒。平平淡淡的调调貌似很耐听。难道和 see g sea b 同理 -. -

> 走廊灯关上 书包放
走到房间窗外望
回想刚买的 书
...
> 铁盒的序变成了日记
变成了空气 演化成回忆

『为什么这样子，蓝星总是转个不停』
『为什么这样子，不练 APM 空气有些安静』

_KISS matters and works._

![image](https://cloud.githubusercontent.com/assets/4962134/20720814/99a65ec2-b69b-11e6-8115-d0e5723d6f4c.png)

呵呵...

**Comment by cosven** [comment]
#### 2016-11-30

> 《归去来兮辞》
> 
> 何则？质性自然，非矫厉所得。饥冻虽切，违己交病。尝从人事，皆口腹自役。于是怅然慷慨，深愧平生之志。
> 三径就荒，松菊犹存。携幼入室，有酒盈樽。引壶觞以自酌，眄庭柯以怡颜。倚南窗以寄傲，审容膝之易安。
> 园日涉以成趣，门虽设而常关。策扶老以流憩，时矫首而遐观。云无心以出岫，鸟倦飞而知还。

_这些东西什么时候学比较好哩..._

-----------

> 《滕王阁序》
> 
> 关山难越，谁悲失路之人；萍水相逢，尽是他乡之客。

_呜呼_

> 时维九月，序属三秋。潦水尽而寒潭清，烟光凝而暮山紫。俨骖騑于上路，访风景于崇阿。临帝子之长洲，得天人之旧馆。层峦耸翠，上出重霄；飞阁流丹，下临无地。鹤汀凫渚，穷岛屿之萦回；桂殿兰宫，即冈峦之体势。
> 披绣闼，俯雕甍，山原旷其盈视，川泽纡其骇瞩。闾阎扑地，钟鸣鼎食之家；舸舰迷津，青雀黄龙之舳。云销雨霁，彩彻区明。落霞与孤鹜齐飞，秋水共长天一色。渔舟唱晚，响穷彭蠡之滨，雁阵惊寒，声断衡阳之浦。

_你在我 16 岁的时候跟我说：这很美，我是不太懂的... 555_

> 嗟乎！时运不齐，命途多舛。冯唐易老，李广难封。屈贾谊于长沙，非无圣主；窜梁鸿于海曲，岂乏明时？

_想起当年同桌每天读这序，_

> 《箜篌谣》
> 结交在相知，骨肉何必亲。

_大概是吧，tmp I_ 🤔

#### 早起听歌...

哈哈哈，😁 想起一首歌：《All over the world - Françoise Hardy》_的一句歌词_...

**Comment by cosven** [comment]
#### 2016-12-01

嘿嘿，12 月份喽，哇咔咔

##### How We Deploy Python Code
<https://nylas.com/blog/packaging-deploying-python>
> Building, packaging, and deploying Python using versioned artifacts in Debian packages

git+pip -> virtualenv (不好做版本控制) -> docker(基础设施不支持) -> debian package

**Comment by cosven** [comment]
#### 2016-12-05

##### 今日
1. 请养成及时回邮件的习惯
2. feeluown 已经快两个月没有动过了

##### neovim
msgpack？dbus？http？恩，瞄了一眼

来来来，feeluown-core 是应该动手写写了， 但是这年纪不想折腾啊，懒癌，额。但是说好的炫酷呢 -/ -

##### 思维不连续
- MAKE LOVE - BIGBANG
- just a dream - Jason Chen
满满的高中回忆，好久没有联系过那个啥，好基友...。。。

##### 明日（这个是看到上上面那个标题想的）
于是有了 明日复明日，明日何其多。

##### 00：00
零点过零分，等黑夜吞噬啊啊啊啊啊

今日被两 colleague 都不约而同的夸了一番，意料之外。（感受到了浓浓的奇怪的味道）

本来不想写，因为感觉今日并没有什么好记下来的，结果就是以后某天来看的时候，会想：这天发生了啥事情么？貌似没有把。删掉吧....

However，秉着『笑一笑，十年少』的原则。还是记录一下，或许几天之后还记得今天，无忧无喜的日子还是难得，好把 -. -

恩，写日记的时候，一定要听 cheerful 的歌曲。一定要把灯打开（丑八怪咿呀咿呀，别把灯打开...厉害了）。一定不要听诸如『荒岛-谢春花』这首...

问题来了，眼镜有点累了，脑袋很活跃，手也灵活。但是按的都是 Delete 键啊 -

为什么说一天要 工作+运动+娱乐呢，那样就不需要动脑了，然后就轻松了。恩，根据以往经验，不要在夏天中午睡觉，不要在深夜想问题，不要早上赖床，少写日记多看书。

趁现在感慨一句还不会🔥：~~为什么这年代，人都要结婚啊？不能愉快的一个人生活嘞，为啥社会创造不出这样的环境呢？共产主义社会可以么.... 哈哈哈哈哈哈哈哈。~~ 恩，这想法不对，要改，不然💊 。

很多事情都是有目的性的，但是很多也是顺其自然发生的。而且很多有目的性的事情中会顺其自然的夹杂无目的性的事情。

菩提本无树，明镜亦非台，本来无一物，何处惹尘哎： 简单的事情不要看复杂了。这样来说：计算机科学家发明的 KISS 原则是不是比这个更底层... Abstract Base Class...

说好的要提升表达能力呢，这样乱写真的可以么.... 🙄...
Why would I ever... 这句话突然就冒出来了，待我等下写完查下歌词，但是写完最可能的结果是直接躺。这一天我什么都不想干。恩，不错，感觉已经把歌词=歌名给串成一段话了。。此处应有掌声。恩，人就是这样寻开心的... smile ...

好，这声音很好地让我有了结束的理由

**Comment by cosven** [comment]
#### 2016-12-08

##### 666 as expected 555

> 昨晚下了一整夜的雨
今早起来却能看见好天气
一个晚上解不出的迷
在早之后不用再深究谜底
`厉害了 - 菇凉`

`如果中年有了啥病，我想被一巴掌打史 -. -` 先立 flag... 补：如果不影响

**Comment by cosven** [comment]
#### 2016-12-12
补
##### rst and sphinx -> docs

##### weather
空气和天气都很差，但是秋裤很热。
`阴霾天空，隐约`... 感觉我越来越厉害了...
🤔

感觉都是爆炸的节奏 💥...

**Comment by cosven** [comment]
#### 2016-12-13
##### 论积极与消极
`唧唧唧复唧唧，木兰当户织...` 

##### 论 Emacs 与 Vim
用了一天 Emacs，然后切到 Vim。
神清气爽...心旷神怡...
但是别人是操作系统... 🙄

##### 论运维 - 磁盘
`df -h`
`du -hi`
`ncdu` -> _脑残 du_....

##### what should be put in a try...catch... clause?

**Comment by cosven** [comment]
#### 2016-12-21
竟然隔了 8 天，OMG ! 竟然断了这么久，惊呆
pia！pia！pia！

##### DevOps
<http://mp.weixin.qq.com/s/nFbxAhTulzHen8Qtr0xrkw>

- [ ] 感觉可以扒一扒其中的一些概念...和...一些扯淡的总结

`Application Ops` ？
DevOps 自动化，可以认为是从应用的角度，构建一个安全、快速且可持续的变更过程，这个地方包括版本发布、升级、回滚等等，当前业界最佳标准实践是 **持续交付**。

##### http cache
<http://mp.weixin.qq.com/s/qOMO0LIdA47j3RjhbCWUEQ>
感觉 debug 用得到...

`Cache-Control`, `Last-Modified`, `Date` 三个字段值的理解

1. 缓存存储策略
2. 缓存过期策略
3. 缓存对比策略

##### 没有什么概括的总结（正常的大冒险为啥就这么有趣哩）

恩，所以

- 信用卡貌似用处并不大
- [ ] 貌似应该想想有什么可以持续研究（玩）的东西？
- [ ] Vue.js 到底哪里好嘞？所以 react 为啥不好哩... mentor 大法腻害了...
- 第一本要看完的书应该是 **Python Cookbook 3**
- 凭什么这个行业需要加班哩 ？
- 人们是怎样做到 就算是坐在旁边或者对面 但也通过 IM 软件来交流的？不过这样确实能不打断听歌...恩，还不错....
- 为什么我有种 我需要带别人的赶（错）脚（觉）？晕... 不过，这貌似是推动修 bug 的最大的动力..额

不想熬夜，但想学习，但又起得晚。就算起得早也是折腾，各种刷刷刷。这就尴尬了...

还有
1. 不会分（甩）任务
2. 不会（够）带人啊，而且也不应该出现这种事情吧......额......真晕
3. 其他事情，能干什么哩，额，好奇
恩，结论就是，做 leader 的一定要把任务说明白哩：我不想猜猜猜啊，晕 +_+

为啥感觉需要今晚就把明天的事情给想好呢....额，累，晕。恩，但是如果充实一点的话，也不是什么坏事...但是我是老人...tut...

。。恩，总感觉还有些啥没记下来，不过也不想管了，只想睡觉...

恩，说好的看一小节书；看一小段视频；写一段明天『_交接_』的纲要呢，哎，睡睡睡... 晕

**Comment by cosven** [comment]
#### 2016-12-23

转眼就 _黑色星期五_ 了.. 不懂业界为什么会有这种说法？

今日难题：如果计算如下加法的结果

```
5omA5Lul6Zeu6aKY5YW25a6e5bqU6K+l5piv6L+Z5qC355qE77ya5oiR6KeJ5b6X5pma5LiKIF/nibnmhI9fIOWOu+aOpeW8guaAp+aci+WPi+Wbnuadpe+8jOeul+aYr+S4gOenjeavlOi+g+S6suWvhueahOihjOS4uuOAguWPr+S7peeul+aYr+S4gOenjeWfuuS6jueJueWumuWFs+ezu+aJjeS8muacieeahOihjOS4uuWQp+OAguOAguWkp+mDqOWIhuaDheWGteadpeiusu+8jOW6lOivpeaYr+i/meagt+eahOOAguS9huaYr+WRou+8jOW5s+W4uOiHquW3seWBmui/meS6i+eahOaXtuWAme+8jOS4jemcgOimgeWSjOWIq+S6uuino+mHiu+8jOeEtuWQjuaIkeWPr+S7peabtOWKoOaEn+aAp+eahOaAneiAg+i/meS4qumXrumimO+8jOaci+WPi+mcgOimgeW4ruWKqe+8jOeQhuaJgOW9k+eEtuWWve+8jOe7meS6iOW4ruWKqeWRgOOAguaNouS9jeaAneiAg+WYm++8jOiHquW3seS4gOS4quS6uuWNiuWknOWKoOePreWbnuadpe+8jOS9oOaDs+m7mOm7mOeahOS4gOS4quS6uui1sOWbnuadpe+8jOi/mOaYr+acieS4quaci+WPi+mZquedgOWQl+OAguaJgOS7peS5n+S4jeaYr+S4gOWumuimgeWfuuS6juafkOenjeeJueauiuWFs+ezu+WViuOAgi0tLS0tLSDmiYDku6Xpl67popjmnaXkuobvvIzlpoLmnpzkvaDpnIDopoHlkozliKvkurrop6Pph4rov5nkuKrooYzkuLrvvIzlpb3lg4/lh6DkuY7mmK/kuI3lj6/og73op6Pph4rmuIXmpZrnmoTjgILkvaDop6Pph4rlj6rmnInkuIDnp43nu5PmnpzvvIzlsLHmmK/lhbPns7vkuI3mraPluLjjgILmganvvIzmiYDku6XvvIzov5nkuovmg4XlsLHmjLrlsLTlsKznmoTvvIzmiJHop4nlvpfkuKTpnaLpg73lvojpmr7lgZrkurrllYrjgILmiYDku6XlmJvvvIzku6XliY3lsLHmg7Pov4fkuIDkuKrpl67popjvvJrnu5PkuqTlhbPns7vpnZ7luLjpnZ7luLjlpb3nmoTlvILmgKfmnIvlj4vvvIzmnIDlpb3ov5nkuKrmnIvlj4vkuZ/mmK/ot5/kvaDlh7rkuo7lkIzmoLfnmoTnirbmgIHvvIxhbG9uZe+8jOi/meagt++8jOaEn+aDheWPr+S7peW+iOa3seWViu+8jOS5n+WPr+S7peS6p+eUn+aEn+aDhe+8jOS5n+WPr+S7peW+iOe6r+eyue+8jOWwseW+iOmaj+aEj+WViuOAguS4jemcgOimgeWSjOWIq+S6uuino+mHiuS7gOS5iO+8jOS4jemcgOimgeeuoeWIq+S6uuaAjuS5iOaDs+eahOOAguS4pOS6uuefpemBk+WwseWlve+8jOS9huaYr+WmguaenOS4jeaYryBhbG9uZSDnmoTnirbmgIHvvIzmgLvmmK/kvJrmnInkuIDkupvnpL7kvJrmiJbogIXlv4PnkIbljovlipvlkKfvvIzlj43mraPlgZrkuovkvJrmnInmiYDpob7lv4zjgILmganjgILlhrPlrprmiorov5nmrrXmlofku7YgZW5jb2RlIOS4gOS4i+OAgg
```

恩，今天，准确说昨天，有一个领悟：怎样也不能甩锅给自己的大小伙伴，甚至可以主动背锅啊。（论信任是怎样炼成的）想起一个事：日常感觉 little leader 不是那么有领导力，但是最少你可以感受到他心是向 team 内的。

##### jenkins-swarm 到底能不能用嘛
我突然发现，这个 Q TMD 还有一个星期，ca....

所以明天在研究下 jenkins-swarm 的能力到底有多强就能得出一个大概的方案了吧。

##### 😪
恩，早睡早起是个好习惯。恩，我要早睡早起。于是愉快的去睡了。。。

##### 所以周末可以整理几个东西
恩，既然想到，就提前规划一下喽

1. python cookbook 3。可以看个一两节啊，写点代码啥的。做一道算法题啊
2. 关注一下租房、工资、招聘等等事情啊
3. 感觉可以买点书回来看看 -> 文学书 + python cookbook ?
想想阳光照进来的下午，翻着书，应该会比较惬意把，最少它本身是不错的。

为啥现在没人写文言文了呢，哎

```
悦亲戚之情话，乐琴书以消忧。农人告余以春及，将有事于西畴。或命巾车，或棹孤舟。既窈窕以寻壑，亦崎岖而经丘。木欣欣以向荣，泉涓涓而始流。善万物之得时，感吾生之行休。
```
最近感觉这篇总是从脑子里冒出来。 恩，腻害了。要我就把后面两句去掉了...

```
天之苍苍，其正色邪？其远而无所至极邪？
...
小知不及大知，小年不及大年。奚以知其然也？朝菌不知晦朔，蟪蛄不知春秋，此小年也。楚之南有冥灵者，以五百岁为春，五百岁为秋。上古有大椿者，以八千岁为春，八千岁为秋。此大年也。而彭祖乃今以久特闻，众人匹之。不亦悲乎！
```
很帅...但是有点难记... 反正用纸记下来当然好喽，但是记不了这么多，等下次看到有个印象也是极好的。

**Comment by cosven** [comment]
#### 2016-12-24
总是记录过去的事情貌似并不能满足我等高端的需求了...
人有预见未来的能力么.... 反正我是准备愉快地记下了明天的事情了。

> 今日天气不错，空气状况也还不错。我睡到了上午十点，发现周围并没啥动静。于是想了下，还是睡吧，但是睡不着啊，恩，起来听一波山歌？古典乐？恩，还是先玩一把游戏坑坑队友？
恩，最后选择了看一波视频的我。应该是出去溜达了一圈，但是外面太冷，刚出门就有了回头的冲动。想着出去也没啥事情可以干啊... 为什么要自虐呢？于是老实的跑回家里，在群里吼了一声... 然并暖，“这群混蛋竟然都还没有起床... 好气”
恩，想到天气如此之好，明天就有雾霾了，要不今天去逛逛公园，于是我决定去心仪已久但貌似实际上并没有啥吸引力的颐和园... 路上经过北大的时候，我在想，要不感受下大学生活吗。
12-23 毕。

既然能预见一日。两日也只是量的差别吧。

> 今日天气很差，北京应该没有人想主动出门！12-24 毕 恩，貌似这天的生活很简单也很舒适。
但是好像不太对，今天是我生日... 额，晕

白色耳机 -> 黑色耳机 -> 外放 -> 黑夜 -> 白色耳机 的循环有点刺激。我是在为人类耳朵的进行压测么...

耳边响起一首：风になる - つじあやの - 恋恋风歌 <http://music.163.com/#/song?id=643034>
恩，还不错嘛

**Comment by tristawang** [comment]
test

**Comment by tristawang** [comment]
2016-12-24

> 今天天气不错，空气状况也不错。我睡到了上午十点。打开游戏发现没有人，然后自己玩到中午。点了一波外卖，睡了个午觉，嗯。醒来三点多。出不出去呢，出去太晚了，老司机们上线了，愉快的打了局游戏。晚饭点了诶，据说今天平安夜？嗯，要不要吃个苹果。算了吧，继续点了波外卖。要不要看个视频？写点文档？算了，听会儿音乐看会儿书吧。嗯，夜深了诶，睡个觉。明天？明天是不是要请大家吃饭？还要定地方？好烦诶。。。B: **到时候再说喽，恩**

> 竟然喝醉了诶。。尴尬么？蚊子：尴尬的说 小柒：哪里尴尬了，另外，酒品超级棒

**Comment by cosven** [comment]
#### 2016-12-26

**Comment by cosven** [comment]
#### 2016-12-27
腻害了

> 所以为什么厉害了呀 这么晚睡 差评 -- by 小柒

##### 让我回忆一下是怎样说服 leader 改变目标的...

l: 我们要做到水平扩容
m: 这个目前不是我们的痛点
l: 我是想让你们不要下个 Q 在 jenkins 上不要收到太多的 on-call
l: ....
m: ....
l: 所以平常最担心的是什么
m: 担心 master 挂掉...
l: 那就先解决 master 高可用的问题吧...
l: 下个 Q 想干啥呢？
> OS: 感觉自从上次说自己想写 py 代码，然后貌似写代码的任务都分给了我... 
> 哦咦 😯，但是看了几天 Jenkins Slides，才刚刚感觉自己稍微深入了一点哩...
> 恩，但是规模不大，确实这个需求就是不紧急诶... 所以说... 恩，规模还是挺重要的...
> 哦咦，所以到底想干啥工作呢。写代码 + 喜欢自动化、工具 => 所以选了 ep  => 然后做了 (tooling, middleware, framework, CI/CD) 的事情 => 然后，恩

所以就是这样么？晕...

##### 惊奇
时隔 3 月，组内的人又再次聚在一起了...

**Comment by yannnli** [comment]
up 一下 不如还我这个号好了。。。- -那个邮箱我常年不用 嗯 这是个totally新号

**Comment by yannnli** [comment]
厉害诶

**Comment by cosven** [comment]
#### 2016-12-28

大早上的，这电脑为什么开始放歌了，💊

##### flask + sql + migrate

###### sqlalchemy: Numeric vs Float vs Double ?
<http://stackoverflow.com/questions/618535/difference-between-decimal-float-and-double-in-net>
`float` 和 `double` 带精确度，double 能表示的数更多
`decimal` 能表示的数据的大小和 `double` 相当
> The Numeric type is designed to receive data from a database type that is explicitly known to be a decimal type (e.g. DECIMAL, NUMERIC, others) and not a floating point type (e.g. FLOAT, REAL, others). 
> We use DECIMAL data type to store exact numeric values, where we do not want precision but exact and accurate values. 

##### 嘿嘿嘿
<https://v.douyu.com/show/YAox276dgNWVz8ZQ>

论大哥与辅助...
论傻乐..
论轻度抑郁...
论接/送礼物 - 言谢...
论砒霜与鸡汤......
雪崩 vs 爆炸 那个比较厉害...

想起前几天有位大师说的『或许』有道理，性格太相似的同异性人类大概只适合互相理解和愉快玩耍。嘿嘿... 谁知道大师在想什么... 哈哈

>Qi:  _一直在思考这是不是一个伪命题。但反正我是以失败佐证了。但证明是需要严格推导的不是么=m=_

不过，思考：
> 声音不好听的话，恩，的确，我才不听呢..,[此处应有苦笑...捂脸]
但是光声音好听，我也不会听呀...恩，这就有道理了...

>Qi: _所以苦笑face是个什么鬼_

怎么感觉晚上键盘格外好用哩...

大兄弟，说好的写代码呢  》。《

#### 2016-12-29

想起当年（诶，当年的英语是啥，总感觉这句话很傻诶.... In those years，然而英语口语差也没用啊）
>Qi: _When it comes to those years?我也是猜的。。。。23333_

一个通宵就 `nobody - wonder girls` `心痛 2009 - 欢子` `哥只是个传说 - 陈旭` 三首歌，无限循环...

#### 2016-12-30

只能说晚上写代码效率就是高一点啊...
熬夜竟然是为了写公司的业务代码... gg
但是，为啥最近感觉键盘和鼠标贼好用额... gg

恩，还没有搞卫生！没有打扫沙发啥的！没有规划各种路线！【恩，此处应有叹息】
POI，还是滚去睡把... （虽然感觉现在莫名的紧张？激动？脑残？en，大概是脑残... 不想上床，虽然感觉一倒马上就能呼呼呼...）

明天：
- 提 PR，等 review
- 等联调
- 有 bug => 小 leader 修
- 吃完饭，走人...
- 晚上看情况找个地方吃饭...
- 准备睡觉事宜... 【尴尬】
- 准备游玩事宜... 【OS：准备个蛋蛋】

POI 神奇的地球。pu...

#### 2016-12-31
感觉会有点刺激... 
知之为知之，不知为不知
然.
